version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - DS_PYTHON_IMG_VERSION=$(head -n 1 ./.ds_python_version)
      - docker build --build-arg="DS_PYTHON_IMG_VERSION=${DS_PYTHON_IMG_VERSION}" -t ${REPOSITORY_URI}:latest .
      - docker push ${REPOSITORY_URI}
  post_build:
    commands:
      - echo Build completed!
