version: 0.2
phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${FIPS_REPOSITORY_URI}
      - export COMMIT_HASH_SHORT="$(echo $COMMIT_HASH | cut -c 1-7)"
      - echo Building the Docker image...
      - echo $FIPS_REPOSITORY_URI
      - echo $COMMIT_HASH_SHORT
      - echo $BRANCH_NAME
      - export DS_PYTHON_IMG_VERSION=$(head -n 1 ./.ds_python_version)
      - docker build --build-arg="DS_PYTHON_IMG_VERSION=${DS_PYTHON_IMG_VERSION}" --tag ${FIPS_REPOSITORY_URI}:${COMMIT_HASH_SHORT} --tag ${FIPS_REPOSITORY_URI}:${BRANCH_NAME} .
      # We have a life cycle policy in place to expire and delete images from dev branches,
      # so there are no issues with pushing as many of these images as there may be.
      - docker image push --all-tags ${FIPS_REPOSITORY_URI}
  post_build:
    commands:
      - echo Build completed!
      - printf '{"tag":"%s"}' $COMMIT_HASH_SHORT > build.json
