version: 0.2
phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - echo Logging into Docker Hub
      - echo $DOCKERHUB_PASSWORD | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
      - echo Building the Docker image...
      - PATCH_TAG=${TAG_NAME#"v"} # major.minor.patch
      - MINOR_TAG=${PATCH_TAG%.*} # major.minor
      - MAJOR_TAG=${MINOR_TAG%.*} # major
      - export DS_PYTHON_IMG_VERSION=$(head -n 1 ./.ds_python_version)
      - docker build --build-arg="DS_PYTHON_IMG_VERSION=${DS_PYTHON_IMG_VERSION}" -t ${REPOSITORY_URI}:${PATCH_TAG} -t ${REPOSITORY_URI}:${MINOR_TAG} -t ${REPOSITORY_URI}:${MAJOR_TAG} -t civisanalytics/civis-jupyter-python3:${PATCH_TAG} -t civisanalytics/civis-jupyter-python3:${MINOR_TAG} -t civisanalytics/civis-jupyter-python3:${MAJOR_TAG} .
      - docker image push --all-tags ${REPOSITORY_URI}
      - docker image push --all-tags civisanalytics/civis-jupyter-python3
  post_build:
    commands:
      - echo Build completed!
      - printf '{"tag":"%s"}' $TAG_NAME > build.json
