version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            DS_PYTHON_IMG_VERSION=$(head -n 1 ./.ds_python_version) docker build --build-arg="DS_PYTHON_IMG_VERSION=$DS_PYTHON_IMG_VERSION" -t civisanalytics/civis-jupyter-python3 .
      - run: docker run civisanalytics/civis-jupyter-python3 /bin/bash -c "echo BUILDS OK"
      - run: docker run civisanalytics/civis-jupyter-python3 python -c "import civis"
