version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: docker build -t civisanalytics/civis-jupyter-python3 .
      - run: docker run civisanalytics/civis-jupyter-python3 /bin/bash -c "echo BUILDS OK"
      - run: docker run civisanalytics/civis-jupyter-python3 python -c "import civis"
